name = "CentralDiff"
uuid = "90920290-6b84-416f-a7d1-b42757e548f9"
authors = ["Taketo Tominaga"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
